export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: ['**/*.test.ts'],
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  coveragePathIgnorePatterns: ['/node_modules/', '/dist/', '/prisma/'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/config/database.ts',
    '!src/config/redis.ts',
    '!src/config/env.ts',
    '!src/config/logger.ts',
    '!src/types/**/*.ts',
    '!src/app.ts',
    '!src/server.ts',
    '!src/services/pdf-generator.service.ts',
    '!src/services/invoice-pdf.service.ts',
    '!src/services/product-import.service.ts',
    '!src/services/arca-wsaa.service.ts',
    '!src/providers/invoice/facturante.provider.ts',
    '!src/providers/invoice/arca-direct.provider.ts',
    '!src/middleware/rate-limit.ts',
    '!src/utils/secure-config.ts',
    '!src/routes/**/*.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'json', 'html'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testTimeout: 10000,
  verbose: true,
};